name: 'nba_analysis'
version: '1.0'

profile: 'nba_analysis'


model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
analysis-paths: ["analysis"]

target-path: "target"  # Directory where dbt will write JSON artifacts
clean-targets:         # Directories that dbt will remove before running
  - "target"
  - "dbt_modules"
